/*
 * This file is generated by jOOQ.
*/
package org.jooq.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.db.Indexes;
import org.jooq.db.Keys;
import org.jooq.db.Selecao;
import org.jooq.db.tables.records.EnFlywaySchemaVersionRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnFlywaySchemaVersion extends TableImpl<EnFlywaySchemaVersionRecord> {

    private static final long serialVersionUID = 1452673251;

    /**
     * The reference instance of <code>selecao.en_flyway_schema_version</code>
     */
    public static final EnFlywaySchemaVersion EN_FLYWAY_SCHEMA_VERSION = new EnFlywaySchemaVersion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EnFlywaySchemaVersionRecord> getRecordType() {
        return EnFlywaySchemaVersionRecord.class;
    }

    /**
     * The column <code>selecao.en_flyway_schema_version.installed_rank</code>.
     */
    public final TableField<EnFlywaySchemaVersionRecord, Integer> INSTALLED_RANK = createField("installed_rank", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>selecao.en_flyway_schema_version.version</code>.
     */
    public final TableField<EnFlywaySchemaVersionRecord, String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>selecao.en_flyway_schema_version.description</code>.
     */
    public final TableField<EnFlywaySchemaVersionRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>selecao.en_flyway_schema_version.type</code>.
     */
    public final TableField<EnFlywaySchemaVersionRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>selecao.en_flyway_schema_version.script</code>.
     */
    public final TableField<EnFlywaySchemaVersionRecord, String> SCRIPT = createField("script", org.jooq.impl.SQLDataType.VARCHAR(1000).nullable(false), this, "");

    /**
     * The column <code>selecao.en_flyway_schema_version.checksum</code>.
     */
    public final TableField<EnFlywaySchemaVersionRecord, Integer> CHECKSUM = createField("checksum", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>selecao.en_flyway_schema_version.installed_by</code>.
     */
    public final TableField<EnFlywaySchemaVersionRecord, String> INSTALLED_BY = createField("installed_by", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>selecao.en_flyway_schema_version.installed_on</code>.
     */
    public final TableField<EnFlywaySchemaVersionRecord, Timestamp> INSTALLED_ON = createField("installed_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>selecao.en_flyway_schema_version.execution_time</code>.
     */
    public final TableField<EnFlywaySchemaVersionRecord, Integer> EXECUTION_TIME = createField("execution_time", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>selecao.en_flyway_schema_version.success</code>.
     */
    public final TableField<EnFlywaySchemaVersionRecord, Byte> SUCCESS = createField("success", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * Create a <code>selecao.en_flyway_schema_version</code> table reference
     */
    public EnFlywaySchemaVersion() {
        this(DSL.name("en_flyway_schema_version"), null);
    }

    /**
     * Create an aliased <code>selecao.en_flyway_schema_version</code> table reference
     */
    public EnFlywaySchemaVersion(String alias) {
        this(DSL.name(alias), EN_FLYWAY_SCHEMA_VERSION);
    }

    /**
     * Create an aliased <code>selecao.en_flyway_schema_version</code> table reference
     */
    public EnFlywaySchemaVersion(Name alias) {
        this(alias, EN_FLYWAY_SCHEMA_VERSION);
    }

    private EnFlywaySchemaVersion(Name alias, Table<EnFlywaySchemaVersionRecord> aliased) {
        this(alias, aliased, null);
    }

    private EnFlywaySchemaVersion(Name alias, Table<EnFlywaySchemaVersionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Selecao.SELECAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.EN_FLYWAY_SCHEMA_VERSION_EN_FLYWAY_SCHEMA_VERSION_S_IDX, Indexes.EN_FLYWAY_SCHEMA_VERSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EnFlywaySchemaVersionRecord> getPrimaryKey() {
        return Keys.KEY_EN_FLYWAY_SCHEMA_VERSION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EnFlywaySchemaVersionRecord>> getKeys() {
        return Arrays.<UniqueKey<EnFlywaySchemaVersionRecord>>asList(Keys.KEY_EN_FLYWAY_SCHEMA_VERSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnFlywaySchemaVersion as(String alias) {
        return new EnFlywaySchemaVersion(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnFlywaySchemaVersion as(Name alias) {
        return new EnFlywaySchemaVersion(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EnFlywaySchemaVersion rename(String name) {
        return new EnFlywaySchemaVersion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EnFlywaySchemaVersion rename(Name name) {
        return new EnFlywaySchemaVersion(name, null);
    }
}
