/*
 * This file is generated by jOOQ.
*/
package org.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.db.Indexes;
import org.jooq.db.Keys;
import org.jooq.db.Selecao;
import org.jooq.db.tables.records.EnStatusRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnStatus extends TableImpl<EnStatusRecord> {

    private static final long serialVersionUID = 495520099;

    /**
     * The reference instance of <code>selecao.en_status</code>
     */
    public static final EnStatus EN_STATUS = new EnStatus();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EnStatusRecord> getRecordType() {
        return EnStatusRecord.class;
    }

    /**
     * The column <code>selecao.en_status.seq_status</code>.
     */
    public final TableField<EnStatusRecord, Long> SEQ_STATUS = createField("seq_status", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>selecao.en_status.name</code>.
     */
    public final TableField<EnStatusRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>selecao.en_status</code> table reference
     */
    public EnStatus() {
        this(DSL.name("en_status"), null);
    }

    /**
     * Create an aliased <code>selecao.en_status</code> table reference
     */
    public EnStatus(String alias) {
        this(DSL.name(alias), EN_STATUS);
    }

    /**
     * Create an aliased <code>selecao.en_status</code> table reference
     */
    public EnStatus(Name alias) {
        this(alias, EN_STATUS);
    }

    private EnStatus(Name alias, Table<EnStatusRecord> aliased) {
        this(alias, aliased, null);
    }

    private EnStatus(Name alias, Table<EnStatusRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Selecao.SELECAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.EN_STATUS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EnStatusRecord> getPrimaryKey() {
        return Keys.KEY_EN_STATUS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EnStatusRecord>> getKeys() {
        return Arrays.<UniqueKey<EnStatusRecord>>asList(Keys.KEY_EN_STATUS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnStatus as(String alias) {
        return new EnStatus(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnStatus as(Name alias) {
        return new EnStatus(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EnStatus rename(String name) {
        return new EnStatus(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EnStatus rename(Name name) {
        return new EnStatus(name, null);
    }
}
