/*
 * This file is generated by jOOQ.
*/
package org.jooq.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.db.tables.EnStatus;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnStatusRecord extends UpdatableRecordImpl<EnStatusRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = -110040443;

    /**
     * Setter for <code>task.en_status.seq_status</code>.
     */
    public void setSeqStatus(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>task.en_status.seq_status</code>.
     */
    public Long getSeqStatus() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>task.en_status.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>task.en_status.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return EnStatus.EN_STATUS.SEQ_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return EnStatus.EN_STATUS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getSeqStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getSeqStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnStatusRecord value1(Long value) {
        setSeqStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnStatusRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnStatusRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EnStatusRecord
     */
    public EnStatusRecord() {
        super(EnStatus.EN_STATUS);
    }

    /**
     * Create a detached, initialised EnStatusRecord
     */
    public EnStatusRecord(Long seqStatus, String name) {
        super(EnStatus.EN_STATUS);

        set(0, seqStatus);
        set(1, name);
    }
}
