/*
 * This file is generated by jOOQ.
*/
package org.jooq.db;


import javax.annotation.Generated;

import org.jooq.db.tables.EnFlywaySchemaVersion;
import org.jooq.db.tables.EnStatus;
import org.jooq.db.tables.EnTask;


/**
 * Convenience access to all tables in task
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>task.en_flyway_schema_version</code>.
     */
    public static final EnFlywaySchemaVersion EN_FLYWAY_SCHEMA_VERSION = org.jooq.db.tables.EnFlywaySchemaVersion.EN_FLYWAY_SCHEMA_VERSION;

    /**
     * The table <code>task.en_status</code>.
     */
    public static final EnStatus EN_STATUS = org.jooq.db.tables.EnStatus.EN_STATUS;

    /**
     * The table <code>task.en_task</code>.
     */
    public static final EnTask EN_TASK = org.jooq.db.tables.EnTask.EN_TASK;
}
