/*
 * This file is generated by jOOQ.
*/
package org.jooq.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.db.tables.EnFlywaySchemaVersion;
import org.jooq.db.tables.EnStatus;
import org.jooq.db.tables.EnTask;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Task extends SchemaImpl {

    private static final long serialVersionUID = 1692699122;

    /**
     * The reference instance of <code>task</code>
     */
    public static final Task TASK = new Task();

    /**
     * The table <code>task.en_flyway_schema_version</code>.
     */
    public final EnFlywaySchemaVersion EN_FLYWAY_SCHEMA_VERSION = org.jooq.db.tables.EnFlywaySchemaVersion.EN_FLYWAY_SCHEMA_VERSION;

    /**
     * The table <code>task.en_status</code>.
     */
    public final EnStatus EN_STATUS = org.jooq.db.tables.EnStatus.EN_STATUS;

    /**
     * The table <code>task.en_task</code>.
     */
    public final EnTask EN_TASK = org.jooq.db.tables.EnTask.EN_TASK;

    /**
     * No further instances allowed
     */
    private Task() {
        super("task", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            EnFlywaySchemaVersion.EN_FLYWAY_SCHEMA_VERSION,
            EnStatus.EN_STATUS,
            EnTask.EN_TASK);
    }
}
