/*
 * This file is generated by jOOQ.
*/
package org.jooq.db;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.db.tables.EnFlywaySchemaVersion;
import org.jooq.db.tables.EnStatus;
import org.jooq.db.tables.EnTask;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>selecao</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EN_FLYWAY_SCHEMA_VERSION_EN_FLYWAY_SCHEMA_VERSION_S_IDX = Indexes0.EN_FLYWAY_SCHEMA_VERSION_EN_FLYWAY_SCHEMA_VERSION_S_IDX;
    public static final Index EN_FLYWAY_SCHEMA_VERSION_PRIMARY = Indexes0.EN_FLYWAY_SCHEMA_VERSION_PRIMARY;
    public static final Index EN_STATUS_PRIMARY = Indexes0.EN_STATUS_PRIMARY;
    public static final Index EN_TASK_FK_EN_TASK_EN_TASK = Indexes0.EN_TASK_FK_EN_TASK_EN_TASK;
    public static final Index EN_TASK_PRIMARY = Indexes0.EN_TASK_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index EN_FLYWAY_SCHEMA_VERSION_EN_FLYWAY_SCHEMA_VERSION_S_IDX = Internal.createIndex("en_flyway_schema_version_s_idx", EnFlywaySchemaVersion.EN_FLYWAY_SCHEMA_VERSION, new OrderField[] { EnFlywaySchemaVersion.EN_FLYWAY_SCHEMA_VERSION.SUCCESS }, false);
        public static Index EN_FLYWAY_SCHEMA_VERSION_PRIMARY = Internal.createIndex("PRIMARY", EnFlywaySchemaVersion.EN_FLYWAY_SCHEMA_VERSION, new OrderField[] { EnFlywaySchemaVersion.EN_FLYWAY_SCHEMA_VERSION.INSTALLED_RANK }, true);
        public static Index EN_STATUS_PRIMARY = Internal.createIndex("PRIMARY", EnStatus.EN_STATUS, new OrderField[] { EnStatus.EN_STATUS.SEQ_STATUS }, true);
        public static Index EN_TASK_FK_EN_TASK_EN_TASK = Internal.createIndex("FK_en_task_en_task", EnTask.EN_TASK, new OrderField[] { EnTask.EN_TASK.SEQ_EN_STATUS }, false);
        public static Index EN_TASK_PRIMARY = Internal.createIndex("PRIMARY", EnTask.EN_TASK, new OrderField[] { EnTask.EN_TASK.SEQ_TASK }, true);
    }
}
