/*
 * This file is generated by jOOQ.
*/
package org.jooq.db;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.db.tables.EnFlywaySchemaVersion;
import org.jooq.db.tables.EnStatus;
import org.jooq.db.tables.EnTask;
import org.jooq.db.tables.records.EnFlywaySchemaVersionRecord;
import org.jooq.db.tables.records.EnStatusRecord;
import org.jooq.db.tables.records.EnTaskRecord;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>selecao</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<EnTaskRecord, Long> IDENTITY_EN_TASK = Identities0.IDENTITY_EN_TASK;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EnFlywaySchemaVersionRecord> KEY_EN_FLYWAY_SCHEMA_VERSION_PRIMARY = UniqueKeys0.KEY_EN_FLYWAY_SCHEMA_VERSION_PRIMARY;
    public static final UniqueKey<EnStatusRecord> KEY_EN_STATUS_PRIMARY = UniqueKeys0.KEY_EN_STATUS_PRIMARY;
    public static final UniqueKey<EnTaskRecord> KEY_EN_TASK_PRIMARY = UniqueKeys0.KEY_EN_TASK_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<EnTaskRecord, EnTaskRecord> FK_EN_TASK_EN_TASK = ForeignKeys0.FK_EN_TASK_EN_TASK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<EnTaskRecord, Long> IDENTITY_EN_TASK = Internal.createIdentity(EnTask.EN_TASK, EnTask.EN_TASK.SEQ_TASK);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<EnFlywaySchemaVersionRecord> KEY_EN_FLYWAY_SCHEMA_VERSION_PRIMARY = Internal.createUniqueKey(EnFlywaySchemaVersion.EN_FLYWAY_SCHEMA_VERSION, "KEY_en_flyway_schema_version_PRIMARY", EnFlywaySchemaVersion.EN_FLYWAY_SCHEMA_VERSION.INSTALLED_RANK);
        public static final UniqueKey<EnStatusRecord> KEY_EN_STATUS_PRIMARY = Internal.createUniqueKey(EnStatus.EN_STATUS, "KEY_en_status_PRIMARY", EnStatus.EN_STATUS.SEQ_STATUS);
        public static final UniqueKey<EnTaskRecord> KEY_EN_TASK_PRIMARY = Internal.createUniqueKey(EnTask.EN_TASK, "KEY_en_task_PRIMARY", EnTask.EN_TASK.SEQ_TASK);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<EnTaskRecord, EnTaskRecord> FK_EN_TASK_EN_TASK = Internal.createForeignKey(org.jooq.db.Keys.KEY_EN_TASK_PRIMARY, EnTask.EN_TASK, "FK_en_task_en_task", EnTask.EN_TASK.SEQ_EN_STATUS);
    }
}
