/*
 * This file is generated by jOOQ.
*/
package org.jooq.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.db.tables.EnTask;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnTaskRecord extends UpdatableRecordImpl<EnTaskRecord> implements Record4<Long, String, String, Long> {

    private static final long serialVersionUID = 16002859;

    /**
     * Setter for <code>selecao.en_task.seq_task</code>.
     */
    public void setSeqTask(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>selecao.en_task.seq_task</code>.
     */
    public Long getSeqTask() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>selecao.en_task.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>selecao.en_task.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>selecao.en_task.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>selecao.en_task.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>selecao.en_task.seq_en_status</code>.
     */
    public void setSeqEnStatus(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>selecao.en_task.seq_en_status</code>.
     */
    public Long getSeqEnStatus() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return EnTask.EN_TASK.SEQ_TASK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return EnTask.EN_TASK.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return EnTask.EN_TASK.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return EnTask.EN_TASK.SEQ_EN_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getSeqTask();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getSeqEnStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getSeqTask();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getSeqEnStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnTaskRecord value1(Long value) {
        setSeqTask(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnTaskRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnTaskRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnTaskRecord value4(Long value) {
        setSeqEnStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnTaskRecord values(Long value1, String value2, String value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EnTaskRecord
     */
    public EnTaskRecord() {
        super(EnTask.EN_TASK);
    }

    /**
     * Create a detached, initialised EnTaskRecord
     */
    public EnTaskRecord(Long seqTask, String title, String description, Long seqEnStatus) {
        super(EnTask.EN_TASK);

        set(0, seqTask);
        set(1, title);
        set(2, description);
        set(3, seqEnStatus);
    }
}
